spring:
  application:
    name: fornecedor-service
# Configuração do banco de dados
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fornecedor_db}${DB_URL_PARAM:?ssl=false}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
    jpa:
      show-sql: true
      hibernate:
        generate-ddl: true
        ddl-auto: update

# Flyway (ativado)
  flyway:
    enabled: true
    locations: classpath:db/migration

# Configuração do servidor
server:
  port: 8084
  error:
    include-stacktrace: never

# Configuração Swagger
springdoc:
  swagger-ui.path: /api/swagger-ui.html